// GENERATED by scripts/gen-migrations-manifest.mjs — do not edit.
//
// The migrations this build of the code expects to be applied. /api/health compares it
// against the schema_migrations table so a deploy that outran `npm run migrate:prod` is
// visible immediately, rather than surfacing later as a query against a column that is not
// there yet.

export const EXPECTED_MIGRATIONS: readonly string[] = [
  '001_init.sql',
  '002_workout_distance.sql',
  '003_meal_types_and_recipes.sql',
  '004_foods_catalog.sql',
  '005_exercises_and_sets.sql',
  '006_exercise_pattern.sql',
  '007_case_insensitive_names.sql',
  '008_capitalise_catalog_names.sql',
  '009_title_case_catalog_names.sql',
];
